FROM flectrahq/flectra:1.6

LABEL image=codejamninja/flectra:latest \
  maintainer="Jam Risser <jam@codejam.ninja>" \
  base=debian:stretch

COPY flectra_cli_server.py /usr/lib/python3/dist-packages/flectra/cli/server.py
